env:
  browser: true
  es6: true
extends:
  - kensho/javascript
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: 
  react/destructuring-assignment: off
  react/no-array-index-key: off
