backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "First Section", name: "firstSection", widget: "object", fields: [
              {label: 'Main Text', name: 'mainText', widget: 'string'},
              {label: 'Description', name: 'description', widget: 'string'},
              {label: 'Button Text', name: 'buttonText', widget: 'string'},
              {label: 'Image', name: 'image', widget: 'image'},
            ]}
          - {label: "Stock Section", name: "stockSection", widget: "list", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Background Image", name: "backgroundImage", widget: "image"},
              {label: "Stocks", name: "stocks", widget: "list", fields: [
                {label: 'Country', name: 'country', widget: 'string'},
                {label: 'Country Code', name: 'countryCode', widget: 'string'},
                {label: 'Commission', name: 'commission', widget: 'list', fields: [
                  {label: 'Price', name: 'price', widget: 'text'},
                  {label: 'Text', name: 'text', widget: 'text'},
                ]},
              ]}
            ]}
          - {label: "Feature Section", name: "featureSection", widget: "object", fields: [
              {label: 'Main Text', name: 'mainText', widget: 'string'},
              {label: "Sub Text", name: "subText", widget: "string"},
              {label: 'Description', name: 'description', widget: 'string'},
              {label: 'Button Text', name: 'buttonText', widget: 'string'},
              {label: 'Image', name: 'image', widget: 'image'},
            ]}
          - {label: "Blurb", name: "blurb", widget: "object", fields: [
              {label: 'Main Text', name: 'mainText', widget: 'string'},
              {label: "Sub Text", name: "subText", widget: "string"},
            ]}
          - {label: "Real Time Stock Section", name: "realTimeStockSection", widget: "object", fields: [
              {label: 'Main Text', name: 'mainText', widget: 'string'},
              {label: "Description", name: "description", widget: "string"},
              {label: "Button Text", name: "buttonText", widget: "string"},
            ]}
          - {label: "Testimonials", name: "testimonials", widget: "list", fields: [
              {label: "Customer Name", name: "customerName", widget: "string"},
              {label: "Customer Position", name: "customerPosition", widget: "string"},
              {label: "Background Image", name: "backgroundImage", widget: image},
              {label: "Video URL", name: "videoUrl", widget: string},
            ]}
 
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Header Image", name: headerImage, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [
                {label: Title, name: title, widget: string}, 
                {label: Description, name: description, widget: text},
                {label: SecondDescription, name: secondDescription, widget: text},
              ]
            } 
          - {label: "Tabs", name: "tabs", widget: "list", fields: [
              {label: Title, name: title, widget: string},
              {label: Icon, name: icon, widget: image},
              {label: Description, name: description, widget: markdown}
            ]}  
          - {label: 'History Cards', name: historyCards, widget: list, fields: [
              {label: "Date", name: date, widget: string},
              {label: "Description", name: description, widget: string},
            ]}
          - {label: "Investors", name: "investors", widget: "list", fields: [
              {label: "Brand Logo", name: brandLogo, widget: image},
              {label: "Brand Description", name: brandDescription, widget: text}, 
            ]}
          - {label: "Partners", name: "partners", widget: "list", fields: [
              {label: "Brand Logo", name: brandLogo, widget: image},
              {label: "Brand Description", name: brandDescription, widget: text}, 
            ]}

      - file: "src/pages/how-it-works/index.md"
        label: "How it works"
        name: "how-it-works"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "how-it-works-page"}
          - {label: "Header Image", name: headerImage, widget: image}
          - {label: "Sections", name: sections, widget: list, fields: [
              {label: "Title", name: title, widget: text},
              {label: "Description", name: body, widget: markdown},
              {label: "Image", name: image, widget: image},
            ]}
      
      - file: "src/pages/faq/index.md"
        label: "Faq Page"
        name: "faq"
        fields: 
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "faq-page"}
          - {label: "Header Image", name: headerImage, widget: image}
          - {label: "Categories", name: categories, widget: list, fields: [
              {label: "Category Title", name: "categoryTitle", widget: text},
              {label: "Questions", name: questions, widget: list, fields: [
                {label: "Question", name: question, widget: text},
                {label: "Answer", name: answer, widget: text},
              ]},
            ]}
      
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
